# Training
## From Scratch
python -m torch.distributed.run --nproc_per_node=4 image_train.py --data_dir /home/as3ek/data/lizard_split_norm_bright3/ --log_path /scratch/as3ek/NASDM/outputs/lizard_1e4nd_bs40/ --dataset_mode lizard --lr 1e-4 --batch_size 40 --attention_resolutions 32,16,8 --diffusion_steps 1000 --image_size 128 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True --use_checkpoint True --num_classes 7 --class_cond True --no_instance False --lr_warmup_steps 200 --lr_total_steps 100000 --log_interval 100 --save_interval 5000 --lr_decay none
## Finetuning
python -m torch.distributed.run --nproc_per_node=4 image_train.py --data_dir /home/as3ek/data/lizard_split_norm_bright3/ --log_path /scratch/as3ek/NASDM/outputs/lizard_1e4nd70k40bs_2e5nd40bs/ --dataset_mode lizard --lr 2e-5 --batch_size 40 --attention_resolutions 32,16,8 --diffusion_steps 1000 --image_size 128 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True --use_checkpoint True --num_classes 7 --class_cond True --no_instance False --lr_warmup_steps 200 --lr_total_steps 200000 --log_interval 100 --save_interval 5000 --lr_decay none --drop_rate 0.2 --resume_checkpoint /scratch/as3ek/NASDM/outputs/lizard_1e4nd_bs40/model070000.pt

# Finetuning
python -m torch.distributed.run --nproc_per_node=4 image_train.py --data_dir /home/as3ek/data/lizard_split_norm_bright3/ --log_path /scratch/as3ek/github/NASDM/outputs/lizard_1e4nd70k_2e5nd_bs40/ --dataset_mode lizard --lr 2e-5 --batch_size 40 --attention_resolutions 32,16,8 --diffusion_steps 1000 --image_size 128 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True --use_checkpoint True --num_classes 7 --class_cond True --no_instance False --lr_warmup_steps 200 --lr_total_steps 150000 --log_interval 100 --save_interval 5000 --lr_decay none --drop_rate 0.2 --resume_checkpoint /scratch/as3ek/github/NASDM/outputs/lizard_1e4nd_bs40/model075000.pt

# Sample
python -m torch.distributed.run --nproc_per_node=4 image_sample.py --data_dir /home/as3ek/data/lizard_split_norm_bright3/ --dataset_mode lizard_test1 --attention_resolutions 32,16,8 --diffusion_steps 1000 --image_size 128 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True --use_checkpoint True --num_classes 7 --class_cond True --no_instance False --model_path /scratch/as3ek/NASDM/outputs/lizard_1e4nd_bs20/model100000.pt --results_path /scratch/as3ek/samples/syn_test1/ --batch_size 100